# Generated by Django 3.1 on 2020-08-23 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='手机号')),
                ('profession', models.CharField(default='', max_length=128, verbose_name='专业班级')),
                ('school', models.CharField(default='', max_length=128, verbose_name='学校')),
                ('principal', models.CharField(max_length=128, verbose_name='上级负责人')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
                'ordering': ['-add_time'],
            },
        ),
    ]
